copy

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

In [2]:
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
}

details = []
last_page = 0

# Set your range here
for p in tqdm(range(1, 5)):
    url = f"https://www.ambitionbox.com/list-of-companies?page={p}"
    response = requests.get(url, headers=headers)
    
    if response.status_code != 200:
        break

    soup = BeautifulSoup(response.text, 'lxml')
    # Find all company cards first
    cards = soup.find_all('div', class_='companyCardWrapper')

    for card in cards:
        # Basic Info
        name = card.find('h2', class_='companyCardWrapper__companyName').text.strip()
        rating = card.find('div', class_='rating_text').get_text(strip=True)
        desc = card.find('span', class_='companyCardWrapper__interLinking').text.strip()
        logo = card.find('div', class_='companyCardWrapper__companyLogo').img['src']
        
        # Rating Count (e.g., 59.8k)
        rating_count = card.find('span', class_='companyCardWrapper__companyRatingCount').text.strip()
        
        # Tertiary Info (Reviews, Salaries, Jobs, etc.)
        # These are all inside span tags with class 'companyCardWrapper__ActionCount'
        actions = [span.text.strip() for span in card.find_all('span', class_='companyCardWrapper__ActionCount')]
        
        # Safety check: AmbitionBox usually has 6 actions (Reviews, Salaries, Interviews, Jobs, Benefits, Photos)
        reviews = actions[0] if len(actions) > 0 else "0"
        salaries = actions[1] if len(actions) > 1 else "0"
        interviews = actions[2] if len(actions) > 2 else "0"
        jobs = actions[3] if len(actions) > 3 else "0"
        benefits = actions[4] if len(actions) > 4 else "0"
        photos = actions[5] if len(actions) > 5 else "0"

        details.append({
            'Name': name,
            'Rating': rating,
            'Rating_Count': rating_count,
            'Description': desc,
            'Logo_URL': logo,
            'Reviews': reviews,
            'Salaries': salaries,
            'Interviews': interviews,
            'Jobs': jobs,
            'Benefits': benefits,
            'Photos': photos
        })
    
    last_page = p

print(f"Total pages scraped: {last_page}")
print(f"Total items collected: {len(details)}")

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.74it/s]

Total pages scraped: 4
Total items collected: 80

In [4]:
df = pd.DataFrame(details)

In [5]:
df.head()

,Name,Rating,Rating_Count,Description,Logo_URL,Reviews,Salaries,Interviews,Jobs,Benefits,Photos
0,TCS,3.3,(1.1L),IT Services & Consulting | Bangalore / Bengalu...,https://static.ambitionbox.com/assets/v2/image...,1.1L,9.7L,11.7k,3k,10.6k,93
1,Accenture,3.7,(71k),IT Services & Consulting | Bangalore / Bengalu...,https://static.ambitionbox.com/assets/v2/image...,71k,6.5L,9.1k,35.7k,6.7k,48
2,Wipro,3.6,(62.9k),IT Services & Consulting | Hyderabad / Secunde...,https://static.ambitionbox.com/assets/v2/image...,62.9k,4.7L,6.5k,6.6k,4.6k,102
3,Cognizant,3.6,(59.8k),IT Services & Consulting | Hyderabad / Secunde...,https://static.ambitionbox.com/assets/v2/image...,59.8k,5.9L,6.3k,633,5.5k,82
4,Capgemini,3.7,(51.4k),IT Services & Consulting | Bangalore / Bengalu...,https://static.ambitionbox.com/assets/v2/image...,51.4k,4.7L,5.4k,1.8k,3.6k,41

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Create the connection string
# format: mysql+mysqlconnector://user:password@host:port/database
conn_str = "mysql+mysqlconnector://root:password@127.0.0.1:3306/world"

# 2. Create the engine
engine = create_engine(conn_str)

# 3. Read the data (No warning!)
df = pd.read_sql_query("SELECT * FROM city;", engine)

print(df.head())

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [13]:
pd.read_sql_query("SELECT * FROM country WHERE LifeExpectancy > 80 ;",engine)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AND,Andorra,Europe,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,,55,AD
1,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532,JP
2,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454,MO
3,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208,SG
4,SMR,San Marino,Europe,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,None,3171,SM

In [14]:
df = pd.read_csv("IPL Matches 2008-2020.csv")

In [15]:
df.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [22]:
df = pd.read_csv("IPL Matches 2008-2020.csv")

temp = df.groupby("city")["result_margin"].mean().reset_index()
temp

              city  result_margin
0        Abu Dhabi      19.222222
1        Ahmedabad      19.818182
2        Bangalore      23.870968
3        Bengaluru       8.571429
4     Bloemfontein      10.000000
5        Cape Town      27.166667
6        Centurion      10.833333
7       Chandigarh      14.803571
8          Chennai      18.089286
9          Cuttack      13.285714
10           Delhi      17.597222
11      Dharamsala      33.555556
12           Dubai      29.260870
13          Durban      12.800000
14     East London      31.333333
15       Hyderabad      15.507937
16          Indore       9.888889
17          Jaipur      15.787234
18    Johannesburg       7.500000
19          Kanpur       5.500000
20       Kimberley      21.000000
21           Kochi      24.600000
22         Kolkata      14.883117
23          Mumbai      15.790000
24          Nagpur       7.000000
25  Port Elizabeth      31.714286
26            Pune      19.657895
27          Raipur       7.666667
28          Rajkot      13.111111
29          Ranchi       9.285714
30         Sharjah      20.500000
31   Visakhapatnam      24.000000

In [31]:
temp.to_csv('cityIPL.csv', index=False)

pd.read_csv('cityIPL.csv')

              city  result_margin
0        Abu Dhabi      19.222222
1        Ahmedabad      19.818182
2        Bangalore      23.870968
3        Bengaluru       8.571429
4     Bloemfontein      10.000000
5        Cape Town      27.166667
6        Centurion      10.833333
7       Chandigarh      14.803571
8          Chennai      18.089286
9          Cuttack      13.285714
10           Delhi      17.597222
11      Dharamsala      33.555556
12           Dubai      29.260870
13          Durban      12.800000
14     East London      31.333333
15       Hyderabad      15.507937
16          Indore       9.888889
17          Jaipur      15.787234
18    Johannesburg       7.500000
19          Kanpur       5.500000
20       Kimberley      21.000000
21           Kochi      24.600000
22         Kolkata      14.883117
23          Mumbai      15.790000
24          Nagpur       7.000000
25  Port Elizabeth      31.714286
26            Pune      19.657895
27          Raipur       7.666667
28          Rajkot      13.111111
29          Ranchi       9.285714
30         Sharjah      20.500000
31   Visakhapatnam      24.000000

dfd

In [37]:
df = pd.read_csv('cityIPL.csv')
df1 = df.head(10)
df2 = df.tail(10)

In [41]:
with pd.ExcelWriter('output.xlsx') as writer:
    df1.to_excel(writer,sheet_name='batman_1',index=False)
    df2.to_excel(writer,sheet_name='batman_2',index=False)

In [43]:
df.to_html("index.html")

In [49]:
df = pd.read_csv("IPL Matches 2008-2020.csv")
df.head(2)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri

In [62]:
df  = df.groupby(['city','winner'])['result_margin'].sum().unstack()

In [68]:
df.to_json("api.json")
print("hello")

hello

In [64]:
# 1. Create the connection string
# format: mysql+mysqlconnector://user:password@host:port/database
conn_str = "mysql+mysqlconnector://root:password@127.0.0.1:3306/world"

# 2. Create the engine
engine = create_engine(conn_str)

In [67]:
df = pd.read_csv("IPL Matches 2008-2020.csv")
df.to_sql('ipl_winners',engine,if_exists='replace',index=False)

816